name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
      - name: Check formatting with ruff
        run: |
          uvx ruff check .
          uvx ruff format --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --group dev --extra ai
      - name: Run tests
        run: |
          if [ "${{ matrix.python-version }}" = "3.13" ]; then
            uv run --extra ai coverage run -m unittest discover
            uvx coverage report
            uvx coverage xml
          else
            uv run --extra ai python -m unittest discover
          fi
      - name: Submit to Coveralls
        if: matrix.python-version == '3.13'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uvx coveralls --service=github

  test-without-optional-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
      - name: Test import error handling
        run: |
            uv run --isolated --no-extra ai coverage run -m unittest tests.test_ai_providers.test_import_errors
            uvx coverage xml
      - name: Submit to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uvx coveralls --service=github
