name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check formatting with ruff
        run: |
          uvx ruff check .
          uvx ruff format --check .
      - name: Run tests with coverage
        run: |
          uv run coverage run -m unittest discover
          uvx coverage report
          uvx coverage xml
      - name: Submit to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uvx coveralls --service=github
